steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: node
  entrypoint: npm
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: glcoud
  args: ['app', 'deploy']
timeout: "1600s"